name: run-pytest

on: 
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  run-pytest:
    name: run-pytest
    runs-on: ubuntu-latest
    defaults:
          run:
            shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel
    
    - name: Install dependencies
      run: |
        make install
    
    - name: Run tests
      run: |
        make